services:

 grafana2:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - 3053:3000
    user: '472'
    restart: always
    volumes:
     - D:\User\Fork\StudyClub\LionStudyClub\Grafana_Keycloak\grafana\grafana.ini:/etc/grafana/grafana.ini
 influxdb:
    image: influxdb:1.7.2
    container_name: influxdb
    ports:
      - 8086:8086
    restart: always
    #帳號密碼admin/admin

 # zookeeper:
 #  image: wurstmeister/zookeeper
 #  container_name: zookeeper
 #  ports:
 #    - "2179:2181"
 # kafka:
 #   image: wurstmeister/kafka
 #   container_name: kafka
 #   ports:
 #     - "9132:9092"
 #   environment:
 #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
 #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
 #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
 #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
 #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
 #     KAFKA_CREATE_TOPICS: "baeldung:1:1"
 # kafka-ui:
 #    container_name: kafka-ui
 #    image: provectuslabs/kafka-ui:latest
 #    ports:
 #      - 9133:8080
 #    environment:
 #      - KAFKA_CLUSTERS_0_NAME=local
 #      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
 
 # rabbit:
 #    image: rabbitmq:3.8-management
 #    hostname: rabbit
 #    container_name: "rabbit"
 #    restart: always
 #    ports:
 #      - "5672:5672"
 #      - "15672:15672"
 #    environment:
 #      - RABBITMQ_DEFAULT_USER=root
 #      - RABBITMQ_DEFAULT_PASS=123123

 mssql-2022:  
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "mssql-2022"
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
      - MSSQL_PID=Developer # 預設Developer，即開發版的意思
    ports:
      - "1626:1433"

 mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    container_name: "mssqlscripts"
    depends_on:
      - mssql-2022
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql-2022,1626 -U sa -P "Password1*" -Q "create database Keycloak"; do sleep 5; done'
 keycloak2:
   image: quay.io/keycloak/keycloak:23.0.6
   container_name: "keycloak"
   depends_on:
     - mssql-2022
     - mssqlscripts
   command: start-dev
   ports:
     - '8080:8080'
   environment:
     - KC_HOSTNAME=172.20.10.2
     - KC_HOSTNAME_PORT=8080
     - KC_HTTP_ENABLED=true
     - KC_HOSTNAME_STRICT_HTTPS=false
     - KC_LOG_LEVEL=info
     - KEYCLOAK_ADMIN=root
     - KEYCLOAK_ADMIN_PASSWORD=password
     - DB_VENDOR=mssql
     - DB_USER=sa
     - DB_PASSWORD=Password1*
     - DB_ADDR=mssql
     - DB_DATABASE=Keycloak
      
 # jenkins:
 #    image: jenkins/jenkins:lts
 #    restart: unless-stopped
 #    privileged: true
 #    user: root
 #    ports:
 #    - 8081:8080
 #    container_name: jenkins